mariadb:
    image: mariadb:latest
    container_name: sample_mariadb
    environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=sample
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports: 
        - 3306:3306